### PR TITLE
Update pH_fetch_data.cpp

### PR DESCRIPTION
**Pull request by danmrossi**
In this modified code via ChatGPT - Would this work?

We introduce a previousValue variable to store the previously recorded pH value, initializing it to 0.0.

After reading the pH value with pH_sensor.readMeasurement(), we check if the pH value is less than 2.

If the pH value is less than 2, we ignore it, save the previousValue to the file, and print a message indicating that we're using the previous value.

If the pH value is greater than or equal to 2, we save it to the file, update the previousValue, and print a message indicating that the pH value has been saved.

This way, the code will report the previous pH value if the current value is less than 2.

### CODE REVIEW

**Comment by danmrossi** [comment]
screwed up with the github thing just wanted to update the one file lol

**Comment by Sral931** [comment]
I'm afraid that would not work in this context. The program is executed regularly as defined by the pH_service file. That means there is no carry over from the previous execution, each time the program is started with a clean slate.

One could read out the previous value from the pH.dat file however, it would be much more efficient to simply forego updating the file. You can see that done in the fetch_data file, where the save measurement function returns (meaning stops without updating the file) when the value is not a number (NaN) or equal to 0.0

A better update would be to exchange the "equal to 0.0" with the condition "smaller than 1.0".

**Comment by danmrossi** [comment]
Thanks for checking it out I think I will leave the code for you to solve I am already in above my head lol

I think the issue that needs to be resolved in your code is to have it like you say to ignore when NaN or anything under ph 2 including into the -0 territory as for me no logs from reef-pi or anything show any errors only the reading 0.15 which in my situation with this current ph probe and calibration is to do with the calibration offset

Sent from my iPhone

On 2 Oct 2023, at 6:29 pm, Sral931 ***@***.***> wrote:

﻿

I'm afraid that would not work in this context. The program is executed regularly as defined by the pH_service file. That means there is no carry over from the previous execution, each time the program is started with a clean slate.

One could read out the previous value from the pH.dat file however, it would be much more efficient to simply forego updating the file. You can see that done in the fetch_data file, where the save measurement function returns (meaning stops without updating the file) when the value is not a number (NaN) or equal to 0.0

A better update would be to exchange the "equal to 0.0" with the condition "smaller than 1.0".

**Comment by danmrossi** [comment]
i dont know how people code for a living its soo frustrating lol

Would this work instead

I made the following changes:

I modified the condition in the if statement to check if saveValue is either NaN (isnan(saveValue)) or less than 2 (saveValue < 2.0).
If the condition is met (i.e., saveValue is NaN or less than 2), the function returns without saving the value.
With these changes, the code will now check for NaN or values less than 2 before saving the measurement to the file.

void saveToFile(float saveValue, std::string filename){
	// Check if the value is NaN or less than 2
	if (isnan(saveValue) || saveValue < 2.0) {
		// Value does not meet the condition, so return without saving
		return;
	}

	// open file to save value
	std::fstream saveFile;
	saveFile.open(filename, std::ios::out);
	if (saveFile.is_open()) {
		saveFile << saveValue;  // save value
		saveFile.close();  // close file
	}
}

**Pull request closed without merging**
